CREATE TABLE pr_products (
	Product_id INT IDENTITY(1,1)
	,Product NVARCHAR(255) NOT NULL
	,OrderNo NVARCHAR(50) NULL
	,Qty INT NOT NULL DEFAULT(0)
	,CostEx DECIMAL NOT NULL DEFAULT(0)
	,SellEX DECIMAL NOT NULL DEFAULT(0)
	,Tax DECIMAL NOT NULL DEFAULT(0)
	,Supplier_id INT NULL
	,type_id INT NOT NULL DEFAULT(0)
	,expiration_date DATETIME2(7) NULL
	,country_id INT NULL
	,Last_updated DATETIME2(7) NOT NULL DEFAULT(GETDATE())
)