CREATE TABLE sup_supplier (
	Supplier_id INT NOT NULL IDENTITY(1,1)
	,Supplier_name NVARCHAR(255) NOT NULL
	,Contact NVARCHAR(255) NULL
	,Email NVARCHAR(255) NULL
	,Address NVARCHAR(255) NULL
	,Country NVARCHAR(255) NULL
	,Disable BIT NOT NULL DEFAULT(0)
    ,created_on DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE())
	,last_updated DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE())
)