CREATE TABLE sup_supplier (
	Supplier_id INT NOT NULL IDENTITY(1,1)
	,Supplier_name NVARCHAR(255) NOT NULL
	,Contact NVARCHAR(255) NULL
	,Email NVARCHAR(255) NULL
	,Address NVARCHAR(255) NULL
	,Country NVARCHAR(255) NULL
	,Disable BIT NOT NULL CONSTRAINT DF_sup_supplier_Disable DEFAULT(0)
    ,created_on_UTC DATETIME2(7) NOT NULL CONSTRAINT DF_sup_supplier_created_on_UTC DEFAULT(GETUTCDATE())
	,last_updated_UTC DATETIME2(7) NOT NULL CONSTRAINT DF_last_updated_UTC DEFAULT(GETUTCDATE())
)